stages:
  - tagging
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/plugins/sas-message-timestamp"

tagging:
  stage: tagging
  script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git tag ${CI_COMMIT_SHORT_SHA}
    - git push --tags http://${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_BRANCH}

build:
  stage: build
  image: elixir:1.14.5-otp-25
  rules:
    - if: $CI_COMMIT_TAG
  before_script: 
    - apt-get update -y
    - apt-get -y install rsync
    - apt-get -y install zip
  script:
    - make query-deps
    - make
    - DIST_AS_EZS=yes make dist
    - mkdir plugin
    - mv plugins/rabbitmq_message_timestamp-v3.11.x.ez plugin/sas-message-timestamp-${CI_COMMIT_SHORT_SHA}.ez
  cache:
    paths:
      - plugins
  artifacts:
    paths: 
      - plugin

upload:
    stage: upload
    image: curlimages/curl:latest
    rules:
      - if: $CI_COMMIT_TAG
    script:
      - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file plugin/sas-message-timestamp-${CI_COMMIT_SHORT_SHA}.ez ${PACKAGE_REGISTRY_URL}/sas-message-timestamp-${CI_COMMIT_SHORT_SHA}.ez'

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
      - if: $CI_COMMIT_TAG
    script:
      - 'release-cli create --name "sas-message-timestamp-${CI_COMMIT_SHORT_SHA}" --tag-name $CI_COMMIT_SHORT_SHA --assets-link "{\"name\":\"sas-message-timestamp-${CI_COMMIT_SHORT_SHA}.ez\", \"url\":\"${PACKAGE_REGISTRY_URL}/sas-message-timestamp-${CI_COMMIT_SHORT_SHA}.ez\"}"'
